### ISSUE TITLE
Overlapping axes in `show_omega_v2`

### ISSUE THREAD

**Issue by Inosen-Infinity** [AStcherbinine/omegapy#1]
When provided with `Nfig`, function `show_omega_v2` creates new instances of `Axes` instead of getting one from the figure. This leads to separate plots overlapping each other. I managed to fix this by changing
```
ax = plt.axes(polar=True)
```
on line 204 of `omega_plots.py` to
```
if len(fig.get_axes()) == 0:
    ax = plt.axes(polar=True)
else:
    ax = fig.get_axes()[0]
```

**Comment by AStcherbinine** [comment]
Thank you for the report!
I patched it with your solution, and also add security to prevent issues while trying to mix projections.

Added on line 203:
~~~python
if len(fig.get_axes()) != 0:    # If presence of axes
    ax0 = fig.get_axes()[0]
    is_ax0_polar = hasattr(ax0, 'set_theta_offset') # Test if ax has polar projection
    if not polar == is_ax0_polar:
        raise ValueError("Can not mix polar and non-polar projections in the same plot")
~~~
