### ISSUE TITLE
Add BD_Omega as code in useful_functions

### ISSUE THREAD

**Issue by ryanbanderson** [AStcherbinine/omegapy#10]
Since many users will be interested in calculating band depths, it would be nice to include this as a function that can be imported rather than just in the documentation.

**Comment by ryanbanderson** [comment]
Tagging the JOSS thread: openjournals/joss-reviews#6566

**Comment by AStcherbinine** [comment]
I've added the `BD_omega` function in `omega_data` so it can be called with `od.BD_omega` with commit 32f5e911b7b5a149c9a2fbfaf6906050e4a58c43, also deployed with version 3.0.5.
And the documentation has been updated accordingly with 6cffa4c9debc5bfcedc3c26839dd2eecb5106598.
