### ISSUE TITLE
No contribution guidelines  documentation

### ISSUE THREAD

**Issue by Sierra-MC** [AStcherbinine/omegapy#4]
openjournals/joss-reviews#6566

I'm not seeing contribution guidelines documentation or information for users on how to report issues or seek support. For contribution guidelines you may wish to look at https://www.contributor-covenant.org/.

Language from JOSS review requirement: Are there clear guidelines for third parties wishing to 1) Contribute to the software 2) Report issues or problems with the software 3) Seek support

**Comment by AStcherbinine** [comment]
Thank you for pointing that.
A *contributing guidelines* page has been added in the documentation at https://astcherbinine.github.io/omegapy/community/ along with a link in the `README` in commit e77af04c2c05cafb003fc58b12e8d68e20ceee5b

**Comment by Sierra-MC** [comment]
Small typo of old package name in community guidelines. I made a pull request to fix that. Otherwise this looks good to go.

**Comment by AStcherbinine** [comment]
Oops right. Thank you!
