### ISSUE TITLE
Missing example usage

### ISSUE THREAD

**Issue by Sierra-MC** [AStcherbinine/omegapy#5]
Examples in the documentation are missing:

https://astcherbinine.github.io/omegapy/example1_band_depth/
https://astcherbinine.github.io/omegapy/example2_overplot/

I know there is the basic usage examples, but it would be really nice to see these examples as band depth especially is a very common operation that people will want to execute.

openjournals/joss-reviews#6566

**Comment by Sierra-MC** [comment]
Referencing review requirement: Example usage: Do the authors include examples of how to use the software (ideally to solve real-world analysis problems).

**Comment by AStcherbinine** [comment]
Thank you for reminding me to finalize these examples. Both are now published online :

Band depth with commit 1876b099dc231bfd2d5375112140bfc984a9feb8 (https://astcherbinine.github.io/omegapy/example1_band_depth/)
And overplotting with commit 9065f76ba803699ad1897e822953508c330aaf7f (https://astcherbinine.github.io/omegapy/example2_overplot/)

Also, the source code of the `show_data_v2` function has been updated to fix a small bug when overplotting (new module version 3.0.1 published on PyPI)

**Comment by Sierra-MC** [comment]
Is the code for `BD_omega` in `omegapy` itself or is it only in the example usage as source code for users to recreate themselves?

**Comment by AStcherbinine** [comment]
Currently, it's only in the example. The idea was that the users can have the code to either use this function as it, or take it as an inspiration to implement their own band depth (or alternative spectral criteria) computation.

**Comment by Sierra-MC** [comment]
Okay thank you, I just wanted to make sure it wasn't missing or I was not using it incorrectly.
