### ISSUE TITLE
Test coverage?

### ISSUE THREAD

**Issue by Sierra-MC** [AStcherbinine/omegapy#6]
I'm not seeing test coverage in this repository. Is there an available test suite?

openjournals/joss-reviews/issues/6566

**Comment by Sierra-MC** [comment]
Referencing review requirement:
Automated tests: Are there automated tests or manual steps described so that the functionality of the software can be verified?

**Comment by AStcherbinine** [comment]
Thanks for pointing that!

Commit a7a92aee203df2808344c3d099c756740b184a67 added a *Tests* in the documentation going over some tests to check the installation & configuration of the module, along with how to address some potential issues.
https://astcherbinine.github.io/omegapy/tests/

**Comment by Sierra-MC** [comment]
I am finding an error with the version check on the tests page.
```
>>> import omegapy
>>> omegapy.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'omegapy' has no attribute '__version__'
```
On the other hand if I get out of the python console and get back into the terminal I find:
```
(jossreview) sierra@pop-os:~/PycharmProjects/pdr/pdr$ pip freeze|grep omegapy
omegapy==3.0
```
as expected.

**Comment by AStcherbinine** [comment]
Yeah, I added this in a small patch. If you update to go to the current v3.0.4 it should work ;)
Just `pip3 install omegapy --upgrade`

**Comment by Sierra-MC** [comment]
Ah perfect, working now, thanks for the help with that!

**Comment by Sierra-MC** [comment]
```
# OMEGA file importation (ORB0979_3)
omega = od.OMEGAdata('0979_3')

# Atmospheric correction
omega_corr_atm = od.corr_atm(omega_corr)
```
Atmospheric correction in basic usage uses variable `omega_corr` which is not created beforehand. Might be that `omega` should be `omega_corr`. Or there is a missing step?

**Comment by AStcherbinine** [comment]
Ooops, that's on me. It should be `omega` only for both
`omega_corr_atm = od.corr_atm(omega)` and `omega_corr_therm_atm = od.corr_therm_atm(omega, npool=1)` (some leftover from a previous organization of the example...)

Should be updated now.
