### ISSUE TITLE
Recursive file search

### ISSUE THREAD

**Issue by ryanbanderson** [AStcherbinine/omegapy#9]
Given the nested directory structure when data are downloaded from the PSA, it would be nice if calling 
omega = od.OMEGAData('###_#') did a recursive search into subdirectories below the directory specified in omega_bin_path. Or at least add the option.

**Comment by ryanbanderson** [comment]
Tagging the JOSS thread: openjournals/joss-reviews#6566

**Comment by AStcherbinine** [comment]
Thanks for the suggestion!
I've implemented an automatic recursive to handle potential subdirectories, also compatible with having the .NAV and .QUB files not in the same subfolder, as it can be found on the PSA with commit 979b3579b910f68d83429d1f676b5936fdc7fbb9
It has been deployed with version 3.0.5.
